import type { APIClient } from "@/api/client";

export function createTestAPI(overrides: Partial<APIClient> = {}): APIClient {
  return {
    login: async () => ({ id: 1, username: "admin", role: "admin" }),
    logout: async () => undefined,
    me: async () => ({ id: 1, username: "admin", role: "admin" }),
    updateProfile: async (username) => ({ id: 1, username, role: "admin" }),
    changePassword: async () => undefined,
    uploadAvatar: async () => ({ id: 1, username: "admin", role: "admin", avatar: "/api/v1/avatar/admin" }),
    deleteAvatar: async () => ({ id: 1, username: "admin", role: "admin" }),
    getSettings: async () => ({ settings: { version: "v0.0.0-dev" } }),
    updateSettings: async () => undefined,
    search: async () => ({ results: [] }),
    searchStream: async () => undefined,
    detail: async () => ({ id: "1", title: "Demo", episodes: [] }),
    doubanHome: async () => ({ sections: [] }),
    doubanCategories: async () => ({ categories: [] }),
    doubanRecommendFilter: async () => ({ items: [] }),
    playbackURL: async (url) => ({ mode: "direct", url }),
    listSources: async () => ({ sources: [] }),
    createSource: async (source) => ({
      id: 1,
      ...source,
      health: "unknown",
      last_check: "",
      created_at: "",
      updated_at: "",
    }),
    updateSource: async () => undefined,
    bulkSetSourcesEnabled: async () => undefined,
    deleteSource: async () => undefined,
    checkSource: async () => ({ health: "healthy" }),
    checkAllSources: async () => undefined,
    importSources: async () => ({ imported: 0 }),
    listSubscriptions: async () => ({ subscriptions: [] }),
    createSubscription: async (subscription) => ({ id: 1, ...subscription, last_sync: "", updated_at: "" }),
    updateSubscription: async () => undefined,
    deleteSubscription: async () => undefined,
    syncSubscription: async () => undefined,
    listUsers: async () => ({ users: [] }),
    createUser: async (user) => ({
      id: 1,
      username: user.username,
      role: user.role,
      allow_adult_content: user.allow_adult_content ?? false,
    }),
    updateUser: async () => undefined,
    deleteUser: async () => undefined,
    ...overrides,
  };
}
